language: node_js
sudo: true
cache:
  directories:
  - node_modules
node_js: stable
script:
  - npm run lint
  - npm codecov
deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: $CF_USERNAME
  password: $CF_PASSWORD
  name: alchemy-language-demo
  organization: WatsonPlatformServices
  space: demos
  on:
    repo: watson-developer-cloud/alchemylanguage-nodejs
    branch: master